spring:
    server:
        port : 8080
    datasource: 
        url : jdbc:mariadb://localhost:3306/
        username : root
        password : shinhan@3
        driver-class-name : org.mariadb.jdbc.Driver