spring:
    server:
        port : 8080
    datasource: 
        url : mysql://localhost:3306/
        username : root
        password : shinhan@3
        driver-class-name : com.mysql.jdbc.Driver​`